//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEmpty.WebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NecesidadesDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class NecesidadesDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdNecesidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        private System.DateTime FechaCreacionField;
        
        private System.DateTime FechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoContactoField;
        
        private int TipoDonacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoField;
        
        private int IdUsuarioCreadorField;
        
        private int EstadoField;
        
        private System.Nullable<decimal> ValoracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.UsuarioDTO UsuariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.NecesidadesDonacionesInsumosDTO[] NecesidadesDonacionesInsumosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdNecesidad {
            get {
                return this.IdNecesidadField;
            }
            set {
                if ((this.IdNecesidadField.Equals(value) != true)) {
                    this.IdNecesidadField = value;
                    this.RaisePropertyChanged("IdNecesidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((this.FechaFinField.Equals(value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TelefonoContacto {
            get {
                return this.TelefonoContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoContactoField, value) != true)) {
                    this.TelefonoContactoField = value;
                    this.RaisePropertyChanged("TelefonoContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int TipoDonacion {
            get {
                return this.TipoDonacionField;
            }
            set {
                if ((this.TipoDonacionField.Equals(value) != true)) {
                    this.TipoDonacionField = value;
                    this.RaisePropertyChanged("TipoDonacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int IdUsuarioCreador {
            get {
                return this.IdUsuarioCreadorField;
            }
            set {
                if ((this.IdUsuarioCreadorField.Equals(value) != true)) {
                    this.IdUsuarioCreadorField = value;
                    this.RaisePropertyChanged("IdUsuarioCreador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<decimal> Valoracion {
            get {
                return this.ValoracionField;
            }
            set {
                if ((this.ValoracionField.Equals(value) != true)) {
                    this.ValoracionField = value;
                    this.RaisePropertyChanged("Valoracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public ProyectoEmpty.WebService.UsuarioDTO Usuarios {
            get {
                return this.UsuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuariosField, value) != true)) {
                    this.UsuariosField = value;
                    this.RaisePropertyChanged("Usuarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public ProyectoEmpty.WebService.NecesidadesDonacionesInsumosDTO[] NecesidadesDonacionesInsumos {
            get {
                return this.NecesidadesDonacionesInsumosField;
            }
            set {
                if ((object.ReferenceEquals(this.NecesidadesDonacionesInsumosField, value) != true)) {
                    this.NecesidadesDonacionesInsumosField = value;
                    this.RaisePropertyChanged("NecesidadesDonacionesInsumos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UsuarioDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoField;
        
        private int TipoUsuarioField;
        
        private System.DateTime FechaCreacionField;
        
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.NecesidadesDTO[] NecesidadesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int TipoUsuario {
            get {
                return this.TipoUsuarioField;
            }
            set {
                if ((this.TipoUsuarioField.Equals(value) != true)) {
                    this.TipoUsuarioField = value;
                    this.RaisePropertyChanged("TipoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public ProyectoEmpty.WebService.NecesidadesDTO[] Necesidades {
            get {
                return this.NecesidadesField;
            }
            set {
                if ((object.ReferenceEquals(this.NecesidadesField, value) != true)) {
                    this.NecesidadesField = value;
                    this.RaisePropertyChanged("Necesidades");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NecesidadesDonacionesInsumosDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class NecesidadesDonacionesInsumosDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdNecesidadDonacionInsumoField;
        
        private int IdNecesidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.DonacionesInsumos[] DonacionesInsumosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.Necesidades NecesidadesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdNecesidadDonacionInsumo {
            get {
                return this.IdNecesidadDonacionInsumoField;
            }
            set {
                if ((this.IdNecesidadDonacionInsumoField.Equals(value) != true)) {
                    this.IdNecesidadDonacionInsumoField = value;
                    this.RaisePropertyChanged("IdNecesidadDonacionInsumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int IdNecesidad {
            get {
                return this.IdNecesidadField;
            }
            set {
                if ((this.IdNecesidadField.Equals(value) != true)) {
                    this.IdNecesidadField = value;
                    this.RaisePropertyChanged("IdNecesidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ProyectoEmpty.WebService.DonacionesInsumos[] DonacionesInsumos {
            get {
                return this.DonacionesInsumosField;
            }
            set {
                if ((object.ReferenceEquals(this.DonacionesInsumosField, value) != true)) {
                    this.DonacionesInsumosField = value;
                    this.RaisePropertyChanged("DonacionesInsumos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ProyectoEmpty.WebService.Necesidades Necesidades {
            get {
                return this.NecesidadesField;
            }
            set {
                if ((object.ReferenceEquals(this.NecesidadesField, value) != true)) {
                    this.NecesidadesField = value;
                    this.RaisePropertyChanged("Necesidades");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Necesidades", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Necesidades : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdNecesidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        private System.DateTime FechaCreacionField;
        
        private System.DateTime FechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoContactoField;
        
        private int TipoDonacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoField;
        
        private int IdUsuarioCreadorField;
        
        private int EstadoField;
        
        private System.Nullable<decimal> ValoracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.Denuncias[] DenunciasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.Usuarios UsuariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.NecesidadesDonacionesInsumos[] NecesidadesDonacionesInsumosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.NecesidadesDonacionesMonetarias[] NecesidadesDonacionesMonetariasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.NecesidadesReferencias[] NecesidadesReferenciasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.NecesidadesValoraciones[] NecesidadesValoracionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdNecesidad {
            get {
                return this.IdNecesidadField;
            }
            set {
                if ((this.IdNecesidadField.Equals(value) != true)) {
                    this.IdNecesidadField = value;
                    this.RaisePropertyChanged("IdNecesidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((this.FechaFinField.Equals(value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TelefonoContacto {
            get {
                return this.TelefonoContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoContactoField, value) != true)) {
                    this.TelefonoContactoField = value;
                    this.RaisePropertyChanged("TelefonoContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int TipoDonacion {
            get {
                return this.TipoDonacionField;
            }
            set {
                if ((this.TipoDonacionField.Equals(value) != true)) {
                    this.TipoDonacionField = value;
                    this.RaisePropertyChanged("TipoDonacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int IdUsuarioCreador {
            get {
                return this.IdUsuarioCreadorField;
            }
            set {
                if ((this.IdUsuarioCreadorField.Equals(value) != true)) {
                    this.IdUsuarioCreadorField = value;
                    this.RaisePropertyChanged("IdUsuarioCreador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<decimal> Valoracion {
            get {
                return this.ValoracionField;
            }
            set {
                if ((this.ValoracionField.Equals(value) != true)) {
                    this.ValoracionField = value;
                    this.RaisePropertyChanged("Valoracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public ProyectoEmpty.WebService.Denuncias[] Denuncias {
            get {
                return this.DenunciasField;
            }
            set {
                if ((object.ReferenceEquals(this.DenunciasField, value) != true)) {
                    this.DenunciasField = value;
                    this.RaisePropertyChanged("Denuncias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public ProyectoEmpty.WebService.Usuarios Usuarios {
            get {
                return this.UsuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuariosField, value) != true)) {
                    this.UsuariosField = value;
                    this.RaisePropertyChanged("Usuarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public ProyectoEmpty.WebService.NecesidadesDonacionesInsumos[] NecesidadesDonacionesInsumos {
            get {
                return this.NecesidadesDonacionesInsumosField;
            }
            set {
                if ((object.ReferenceEquals(this.NecesidadesDonacionesInsumosField, value) != true)) {
                    this.NecesidadesDonacionesInsumosField = value;
                    this.RaisePropertyChanged("NecesidadesDonacionesInsumos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public ProyectoEmpty.WebService.NecesidadesDonacionesMonetarias[] NecesidadesDonacionesMonetarias {
            get {
                return this.NecesidadesDonacionesMonetariasField;
            }
            set {
                if ((object.ReferenceEquals(this.NecesidadesDonacionesMonetariasField, value) != true)) {
                    this.NecesidadesDonacionesMonetariasField = value;
                    this.RaisePropertyChanged("NecesidadesDonacionesMonetarias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public ProyectoEmpty.WebService.NecesidadesReferencias[] NecesidadesReferencias {
            get {
                return this.NecesidadesReferenciasField;
            }
            set {
                if ((object.ReferenceEquals(this.NecesidadesReferenciasField, value) != true)) {
                    this.NecesidadesReferenciasField = value;
                    this.RaisePropertyChanged("NecesidadesReferencias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public ProyectoEmpty.WebService.NecesidadesValoraciones[] NecesidadesValoraciones {
            get {
                return this.NecesidadesValoracionesField;
            }
            set {
                if ((object.ReferenceEquals(this.NecesidadesValoracionesField, value) != true)) {
                    this.NecesidadesValoracionesField = value;
                    this.RaisePropertyChanged("NecesidadesValoraciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DonacionesInsumos", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DonacionesInsumos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdDonacionInsumoField;
        
        private int IdNecesidadDonacionInsumoField;
        
        private int IdUsuarioField;
        
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.NecesidadesDonacionesInsumos NecesidadesDonacionesInsumosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.Usuarios UsuariosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdDonacionInsumo {
            get {
                return this.IdDonacionInsumoField;
            }
            set {
                if ((this.IdDonacionInsumoField.Equals(value) != true)) {
                    this.IdDonacionInsumoField = value;
                    this.RaisePropertyChanged("IdDonacionInsumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdNecesidadDonacionInsumo {
            get {
                return this.IdNecesidadDonacionInsumoField;
            }
            set {
                if ((this.IdNecesidadDonacionInsumoField.Equals(value) != true)) {
                    this.IdNecesidadDonacionInsumoField = value;
                    this.RaisePropertyChanged("IdNecesidadDonacionInsumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ProyectoEmpty.WebService.NecesidadesDonacionesInsumos NecesidadesDonacionesInsumos {
            get {
                return this.NecesidadesDonacionesInsumosField;
            }
            set {
                if ((object.ReferenceEquals(this.NecesidadesDonacionesInsumosField, value) != true)) {
                    this.NecesidadesDonacionesInsumosField = value;
                    this.RaisePropertyChanged("NecesidadesDonacionesInsumos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ProyectoEmpty.WebService.Usuarios Usuarios {
            get {
                return this.UsuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuariosField, value) != true)) {
                    this.UsuariosField = value;
                    this.RaisePropertyChanged("Usuarios");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NecesidadesDonacionesInsumos", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class NecesidadesDonacionesInsumos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdNecesidadDonacionInsumoField;
        
        private int IdNecesidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.DonacionesInsumos[] DonacionesInsumosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.Necesidades NecesidadesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdNecesidadDonacionInsumo {
            get {
                return this.IdNecesidadDonacionInsumoField;
            }
            set {
                if ((this.IdNecesidadDonacionInsumoField.Equals(value) != true)) {
                    this.IdNecesidadDonacionInsumoField = value;
                    this.RaisePropertyChanged("IdNecesidadDonacionInsumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int IdNecesidad {
            get {
                return this.IdNecesidadField;
            }
            set {
                if ((this.IdNecesidadField.Equals(value) != true)) {
                    this.IdNecesidadField = value;
                    this.RaisePropertyChanged("IdNecesidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ProyectoEmpty.WebService.DonacionesInsumos[] DonacionesInsumos {
            get {
                return this.DonacionesInsumosField;
            }
            set {
                if ((object.ReferenceEquals(this.DonacionesInsumosField, value) != true)) {
                    this.DonacionesInsumosField = value;
                    this.RaisePropertyChanged("DonacionesInsumos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ProyectoEmpty.WebService.Necesidades Necesidades {
            get {
                return this.NecesidadesField;
            }
            set {
                if ((object.ReferenceEquals(this.NecesidadesField, value) != true)) {
                    this.NecesidadesField = value;
                    this.RaisePropertyChanged("Necesidades");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuarios", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Usuarios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoField;
        
        private int TipoUsuarioField;
        
        private System.DateTime FechaCreacionField;
        
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.Denuncias[] DenunciasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.DonacionesInsumos[] DonacionesInsumosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.DonacionesMonetarias[] DonacionesMonetariasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.Necesidades[] NecesidadesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.NecesidadesValoraciones[] NecesidadesValoracionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int TipoUsuario {
            get {
                return this.TipoUsuarioField;
            }
            set {
                if ((this.TipoUsuarioField.Equals(value) != true)) {
                    this.TipoUsuarioField = value;
                    this.RaisePropertyChanged("TipoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public ProyectoEmpty.WebService.Denuncias[] Denuncias {
            get {
                return this.DenunciasField;
            }
            set {
                if ((object.ReferenceEquals(this.DenunciasField, value) != true)) {
                    this.DenunciasField = value;
                    this.RaisePropertyChanged("Denuncias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public ProyectoEmpty.WebService.DonacionesInsumos[] DonacionesInsumos {
            get {
                return this.DonacionesInsumosField;
            }
            set {
                if ((object.ReferenceEquals(this.DonacionesInsumosField, value) != true)) {
                    this.DonacionesInsumosField = value;
                    this.RaisePropertyChanged("DonacionesInsumos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public ProyectoEmpty.WebService.DonacionesMonetarias[] DonacionesMonetarias {
            get {
                return this.DonacionesMonetariasField;
            }
            set {
                if ((object.ReferenceEquals(this.DonacionesMonetariasField, value) != true)) {
                    this.DonacionesMonetariasField = value;
                    this.RaisePropertyChanged("DonacionesMonetarias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public ProyectoEmpty.WebService.Necesidades[] Necesidades {
            get {
                return this.NecesidadesField;
            }
            set {
                if ((object.ReferenceEquals(this.NecesidadesField, value) != true)) {
                    this.NecesidadesField = value;
                    this.RaisePropertyChanged("Necesidades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public ProyectoEmpty.WebService.NecesidadesValoraciones[] NecesidadesValoraciones {
            get {
                return this.NecesidadesValoracionesField;
            }
            set {
                if ((object.ReferenceEquals(this.NecesidadesValoracionesField, value) != true)) {
                    this.NecesidadesValoracionesField = value;
                    this.RaisePropertyChanged("NecesidadesValoraciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Denuncias", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Denuncias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdDenunciaField;
        
        private int IdNecesidadField;
        
        private int IdMotivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentariosField;
        
        private int IdUsuarioField;
        
        private System.DateTime FechaCreacionField;
        
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.MotivoDenuncia MotivoDenunciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.Necesidades NecesidadesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.Usuarios UsuariosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdDenuncia {
            get {
                return this.IdDenunciaField;
            }
            set {
                if ((this.IdDenunciaField.Equals(value) != true)) {
                    this.IdDenunciaField = value;
                    this.RaisePropertyChanged("IdDenuncia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdNecesidad {
            get {
                return this.IdNecesidadField;
            }
            set {
                if ((this.IdNecesidadField.Equals(value) != true)) {
                    this.IdNecesidadField = value;
                    this.RaisePropertyChanged("IdNecesidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int IdMotivo {
            get {
                return this.IdMotivoField;
            }
            set {
                if ((this.IdMotivoField.Equals(value) != true)) {
                    this.IdMotivoField = value;
                    this.RaisePropertyChanged("IdMotivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Comentarios {
            get {
                return this.ComentariosField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentariosField, value) != true)) {
                    this.ComentariosField = value;
                    this.RaisePropertyChanged("Comentarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public ProyectoEmpty.WebService.MotivoDenuncia MotivoDenuncia {
            get {
                return this.MotivoDenunciaField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoDenunciaField, value) != true)) {
                    this.MotivoDenunciaField = value;
                    this.RaisePropertyChanged("MotivoDenuncia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public ProyectoEmpty.WebService.Necesidades Necesidades {
            get {
                return this.NecesidadesField;
            }
            set {
                if ((object.ReferenceEquals(this.NecesidadesField, value) != true)) {
                    this.NecesidadesField = value;
                    this.RaisePropertyChanged("Necesidades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public ProyectoEmpty.WebService.Usuarios Usuarios {
            get {
                return this.UsuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuariosField, value) != true)) {
                    this.UsuariosField = value;
                    this.RaisePropertyChanged("Usuarios");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NecesidadesDonacionesMonetarias", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class NecesidadesDonacionesMonetarias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdNecesidadDonacionMonetariaField;
        
        private int IdNecesidadField;
        
        private decimal DineroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CBUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.DonacionesMonetarias[] DonacionesMonetariasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.Necesidades NecesidadesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdNecesidadDonacionMonetaria {
            get {
                return this.IdNecesidadDonacionMonetariaField;
            }
            set {
                if ((this.IdNecesidadDonacionMonetariaField.Equals(value) != true)) {
                    this.IdNecesidadDonacionMonetariaField = value;
                    this.RaisePropertyChanged("IdNecesidadDonacionMonetaria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int IdNecesidad {
            get {
                return this.IdNecesidadField;
            }
            set {
                if ((this.IdNecesidadField.Equals(value) != true)) {
                    this.IdNecesidadField = value;
                    this.RaisePropertyChanged("IdNecesidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal Dinero {
            get {
                return this.DineroField;
            }
            set {
                if ((this.DineroField.Equals(value) != true)) {
                    this.DineroField = value;
                    this.RaisePropertyChanged("Dinero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CBU {
            get {
                return this.CBUField;
            }
            set {
                if ((object.ReferenceEquals(this.CBUField, value) != true)) {
                    this.CBUField = value;
                    this.RaisePropertyChanged("CBU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ProyectoEmpty.WebService.DonacionesMonetarias[] DonacionesMonetarias {
            get {
                return this.DonacionesMonetariasField;
            }
            set {
                if ((object.ReferenceEquals(this.DonacionesMonetariasField, value) != true)) {
                    this.DonacionesMonetariasField = value;
                    this.RaisePropertyChanged("DonacionesMonetarias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ProyectoEmpty.WebService.Necesidades Necesidades {
            get {
                return this.NecesidadesField;
            }
            set {
                if ((object.ReferenceEquals(this.NecesidadesField, value) != true)) {
                    this.NecesidadesField = value;
                    this.RaisePropertyChanged("Necesidades");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NecesidadesReferencias", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class NecesidadesReferencias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdReferenciaField;
        
        private int IdNecesidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.Necesidades NecesidadesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdReferencia {
            get {
                return this.IdReferenciaField;
            }
            set {
                if ((this.IdReferenciaField.Equals(value) != true)) {
                    this.IdReferenciaField = value;
                    this.RaisePropertyChanged("IdReferencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int IdNecesidad {
            get {
                return this.IdNecesidadField;
            }
            set {
                if ((this.IdNecesidadField.Equals(value) != true)) {
                    this.IdNecesidadField = value;
                    this.RaisePropertyChanged("IdNecesidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ProyectoEmpty.WebService.Necesidades Necesidades {
            get {
                return this.NecesidadesField;
            }
            set {
                if ((object.ReferenceEquals(this.NecesidadesField, value) != true)) {
                    this.NecesidadesField = value;
                    this.RaisePropertyChanged("Necesidades");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NecesidadesValoraciones", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class NecesidadesValoraciones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdValoracionField;
        
        private int IdUsuarioField;
        
        private int IdNecesidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValoracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.Necesidades NecesidadesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.Usuarios UsuariosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdValoracion {
            get {
                return this.IdValoracionField;
            }
            set {
                if ((this.IdValoracionField.Equals(value) != true)) {
                    this.IdValoracionField = value;
                    this.RaisePropertyChanged("IdValoracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int IdNecesidad {
            get {
                return this.IdNecesidadField;
            }
            set {
                if ((this.IdNecesidadField.Equals(value) != true)) {
                    this.IdNecesidadField = value;
                    this.RaisePropertyChanged("IdNecesidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Valoracion {
            get {
                return this.ValoracionField;
            }
            set {
                if ((object.ReferenceEquals(this.ValoracionField, value) != true)) {
                    this.ValoracionField = value;
                    this.RaisePropertyChanged("Valoracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ProyectoEmpty.WebService.Necesidades Necesidades {
            get {
                return this.NecesidadesField;
            }
            set {
                if ((object.ReferenceEquals(this.NecesidadesField, value) != true)) {
                    this.NecesidadesField = value;
                    this.RaisePropertyChanged("Necesidades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ProyectoEmpty.WebService.Usuarios Usuarios {
            get {
                return this.UsuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuariosField, value) != true)) {
                    this.UsuariosField = value;
                    this.RaisePropertyChanged("Usuarios");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MotivoDenuncia", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MotivoDenuncia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdMotivoDenunciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.Denuncias[] DenunciasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdMotivoDenuncia {
            get {
                return this.IdMotivoDenunciaField;
            }
            set {
                if ((this.IdMotivoDenunciaField.Equals(value) != true)) {
                    this.IdMotivoDenunciaField = value;
                    this.RaisePropertyChanged("IdMotivoDenuncia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ProyectoEmpty.WebService.Denuncias[] Denuncias {
            get {
                return this.DenunciasField;
            }
            set {
                if ((object.ReferenceEquals(this.DenunciasField, value) != true)) {
                    this.DenunciasField = value;
                    this.RaisePropertyChanged("Denuncias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DonacionesMonetarias", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DonacionesMonetarias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdDonacionMonetariaField;
        
        private int IdNecesidadDonacionMonetariaField;
        
        private int IdUsuarioField;
        
        private decimal DineroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivoTransferenciaField;
        
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.NecesidadesDonacionesMonetarias NecesidadesDonacionesMonetariasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoEmpty.WebService.Usuarios UsuariosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdDonacionMonetaria {
            get {
                return this.IdDonacionMonetariaField;
            }
            set {
                if ((this.IdDonacionMonetariaField.Equals(value) != true)) {
                    this.IdDonacionMonetariaField = value;
                    this.RaisePropertyChanged("IdDonacionMonetaria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdNecesidadDonacionMonetaria {
            get {
                return this.IdNecesidadDonacionMonetariaField;
            }
            set {
                if ((this.IdNecesidadDonacionMonetariaField.Equals(value) != true)) {
                    this.IdNecesidadDonacionMonetariaField = value;
                    this.RaisePropertyChanged("IdNecesidadDonacionMonetaria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Dinero {
            get {
                return this.DineroField;
            }
            set {
                if ((this.DineroField.Equals(value) != true)) {
                    this.DineroField = value;
                    this.RaisePropertyChanged("Dinero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ArchivoTransferencia {
            get {
                return this.ArchivoTransferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivoTransferenciaField, value) != true)) {
                    this.ArchivoTransferenciaField = value;
                    this.RaisePropertyChanged("ArchivoTransferencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public ProyectoEmpty.WebService.NecesidadesDonacionesMonetarias NecesidadesDonacionesMonetarias {
            get {
                return this.NecesidadesDonacionesMonetariasField;
            }
            set {
                if ((object.ReferenceEquals(this.NecesidadesDonacionesMonetariasField, value) != true)) {
                    this.NecesidadesDonacionesMonetariasField = value;
                    this.RaisePropertyChanged("NecesidadesDonacionesMonetarias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public ProyectoEmpty.WebService.Usuarios Usuarios {
            get {
                return this.UsuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuariosField, value) != true)) {
                    this.UsuariosField = value;
                    this.RaisePropertyChanged("Usuarios");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.WebServiceNecesidadesSoap")]
    public interface WebServiceNecesidadesSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get", ReplyAction="*")]
        ProyectoEmpty.WebService.getResponse get(ProyectoEmpty.WebService.getRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoEmpty.WebService.getResponse> getAsync(ProyectoEmpty.WebService.getRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoEmpty.WebService.getRequestBody Body;
        
        public getRequest() {
        }
        
        public getRequest(ProyectoEmpty.WebService.getRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getRequestBody {
        
        public getRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoEmpty.WebService.getResponseBody Body;
        
        public getResponse() {
        }
        
        public getResponse(ProyectoEmpty.WebService.getResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectoEmpty.WebService.NecesidadesDTO[] getResult;
        
        public getResponseBody() {
        }
        
        public getResponseBody(ProyectoEmpty.WebService.NecesidadesDTO[] getResult) {
            this.getResult = getResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceNecesidadesSoapChannel : ProyectoEmpty.WebService.WebServiceNecesidadesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceNecesidadesSoapClient : System.ServiceModel.ClientBase<ProyectoEmpty.WebService.WebServiceNecesidadesSoap>, ProyectoEmpty.WebService.WebServiceNecesidadesSoap {
        
        public WebServiceNecesidadesSoapClient() {
        }
        
        public WebServiceNecesidadesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceNecesidadesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceNecesidadesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceNecesidadesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoEmpty.WebService.getResponse ProyectoEmpty.WebService.WebServiceNecesidadesSoap.get(ProyectoEmpty.WebService.getRequest request) {
            return base.Channel.get(request);
        }
        
        public ProyectoEmpty.WebService.NecesidadesDTO[] get() {
            ProyectoEmpty.WebService.getRequest inValue = new ProyectoEmpty.WebService.getRequest();
            inValue.Body = new ProyectoEmpty.WebService.getRequestBody();
            ProyectoEmpty.WebService.getResponse retVal = ((ProyectoEmpty.WebService.WebServiceNecesidadesSoap)(this)).get(inValue);
            return retVal.Body.getResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoEmpty.WebService.getResponse> ProyectoEmpty.WebService.WebServiceNecesidadesSoap.getAsync(ProyectoEmpty.WebService.getRequest request) {
            return base.Channel.getAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoEmpty.WebService.getResponse> getAsync() {
            ProyectoEmpty.WebService.getRequest inValue = new ProyectoEmpty.WebService.getRequest();
            inValue.Body = new ProyectoEmpty.WebService.getRequestBody();
            return ((ProyectoEmpty.WebService.WebServiceNecesidadesSoap)(this)).getAsync(inValue);
        }
    }
}
